testString = "This is a test string"
print(testString)
print(testString[10:])
print(testString[:10])
print(testString[10:20])
print(testString[-10:])
print(testString[:-10])
print(testString[-10:-5])
print(testString[-10:20])
print(testString[-10:20:2])
print(testString[::-1])
print(testString[::-2])
print(testString[::2])
print(testString[::-2])
print(len(testString))