from ntpath import join


testString = "    This is a Test String     "
print(testString, ' normal print')
print(testString[10:], ' slicing from 10th index')
print(testString[:10], ' slicing from 0th index')
print(testString[10:20], ' slicing from 10th index to 20th index')
print(testString[-10:], ' slicing from last 10th index')
print(testString[:-10], ' slicing from 0th index to last 10th index')
print(testString[-10:-5], ' slicing from last 10th index to 5th index from last')
print(testString[-10:20], ' slicing from last 10th index to 20th index')
print(testString[-10:20:2], ' slicing from last 10th index to 20th index with step 2')
print(testString[::-1], ' reverse the string')
print(testString[::-2], ' reverse the string with step 2')
print(testString[::2], ' reverse the string with step 2')
print(testString[::-2], ' reverse the string with step 2')
print(len(testString), ' length of the string')
print(testString.replace("test", "testing"), ' replace the string')
print(testString.upper(), ' convert the string to upper case')
print(testString.lower(), ' convert the string to lower case')
print(testString.capitalize(), ' convert the first character of the string to upper case')
print(testString.title(), ' convert the first character of each word to upper case')
print(testString.strip(), ' remove the whitespace from the string')
print(testString.lstrip(), ' remove the whitespace from the left side of the string')
print(testString.rstrip(), ' remove the whitespace from the right side of the string')
print(testString.split(), ' split the string into list')
print('-'.join(testString), ' join the string with -')