userInput = input("Enter something: ")
print(type(userInput))
print("Is there a blank space in the input? {}".format(userInput.isspace()))
print("Is there only numbers in the input? {}".format(userInput.isdigit()))
print("Is there only letters in the input? {}".format(userInput.isalpha()))
print("Is there only alphanumeric in the input? {}".format(userInput.isalnum()))
print("Is there only lowercase letters in the input? {}".format(userInput.islower()))
print("Is there only uppercase letters in the input? {}".format(userInput.isupper()))
print("Is the first letter in the input uppercase? {}".format(userInput.istitle()))
print("Theres {} blank spaces in the input".format(userInput.count(' ')))
print("Theres {} letters A in the input".format(userInput.count('a')))